name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Other steps...

      - name: Lock threads
        uses: dessant/lock-threads@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Other steps...
