name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run dessant/lock-threads@v4
      uses: dessant/lock-threads@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
