name: Main Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
    - name: Run dessant/lock-threads
      uses: dessant/lock-threads@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
