name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cover:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - run: make cover

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: golangci/golangci-lint-action@v2
    - run: make lint

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: golangci/golangci-lint-action@v2
    - run: make format

  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make generate

  tidy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make tidy

permissions:
  security-events: write
