name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  lock-threads:
    runs-on: ubuntu-latest
    steps:
      - name: Lock threads
        uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
