name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up configuration file
      run: echo "${{ secrets.CONFIG_FILE }}" > config_file

    - name: Run make init
      run: sudo make init
