name: Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Make build script executable
        run: sudo chmod +x ./scripts/build_all_service.sh
      - name: Build services
        run: sudo ./scripts/build_all_service.sh

      - name: Translate issues
        uses: usthe/issues-translate-action@v2.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Make stop script executable
        run: sudo chmod +x ./scripts/stop_all.sh
      - name: Stop services
        run: sudo ./scripts/stop_all.sh
