name: Workflow Name

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run dessant/lock-threads
        uses: dessant/lock-threads@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
